---
all:
  children:
    Linux_Servers:
      hosts:
        mbd-rhel10-TP-T440:
          ansible_host: 192.168.1.25
          ansible_user: mderangula

        mbd-ubuntu-os26:
          ansible_host: 192.168.139.63
          ansible_user: maheshbabuderangula
