[Linux_Servers]
mbd-rhel10-TP-T440 ansible_host=192.168.1.25 ansible_user=mderangula ansible_ssh_private_key_file=~/.ssh/id_ansible
mbd-ubuntu-os26 ansible_host=192.168.139.63 ansible_user=maheshbabuderangula ansible_ssh_private_key_file=~/.ssh/id_ansible
